-- Snowflake Automated CDC Streaming Pipeline
CREATE OR REPLACE STAGE S3_TRANSACTIONS_STAGE
  URL = 's3://financial-data-lake-prod/transactions/'
  STORAGE_INTEGRATION = S3_INT_BFSI;

-- Snowpipe auto-ingestion
CREATE OR REPLACE PIPE PIPE_TRANSACTIONS AUTO_INGEST=TRUE AS
COPY INTO STG_TRANSACTIONS
FROM @S3_TRANSACTIONS_STAGE
FILE_FORMAT = (TYPE = 'JSON');

-- Stream on staging table for Change Data Capture
CREATE OR REPLACE STREAM STR_TRANSACTIONS_CDC ON TABLE STG_TRANSACTIONS;

-- Automated task executing every minute on change detection
CREATE OR REPLACE TASK TSK_PROCESS_TRANSACTIONS
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '1 MINUTE'
WHEN
  SYSTEM$STREAM_HAS_DATA('STR_TRANSACTIONS_CDC')
AS
MERGE INTO FACT_TRANSACTIONS T
USING STR_TRANSACTIONS_CDC S
ON T.TXN_ID = S.TXN_ID
WHEN MATCHED AND S.METADATA$ACTION = 'DELETE' THEN DELETE
WHEN MATCHED AND S.METADATA$ACTION = 'INSERT' THEN UPDATE SET
  T.AMOUNT = S.AMOUNT,
  T.STATUS = S.STATUS,
  T.UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED AND S.METADATA$ACTION = 'INSERT' THEN INSERT (
  TXN_ID, ACCOUNT_ID, AMOUNT, STATUS, CREATED_AT
) VALUES (
  S.TXN_ID, S.ACCOUNT_ID, S.AMOUNT, S.STATUS, CURRENT_TIMESTAMP()
);
